// AUTO-GENERATED BY WESL. Original filename: ./alpha.wesl
// @ts-check

// ---
// Value types
// ---

/**
 * @typedef {object} vec3f
 * @prop {'vec3f'} kind
 * @prop {number} x
 * @prop {number} y
 * @prop {number} z
 */

// ---
// Schema types
// ---

/**
 * @typedef {object} F32
 * @prop {'f32'} type
 * @prop {number} __value
 */
const f32 = /**@type{F32}*/ ({
  type: 'f32',
});

/**
 * @typedef {object} Vec3f
 * @prop {'vec3f'} type
 * @prop {vec3f} __value
 */
const vec3f = /**@type{Vec3f}*/ ({
  type: 'vec3f',
});

/**
 * @template T
 * @typedef {object} WgslStruct
 * @prop {'struct'} type
 * @prop {T} props
 */
const struct = /**@type{<T>(props:T)=>WgslStruct<T>}*/ (
  (props) => ({
    type: 'struct',
    props,
  })
);

// ---
// Function types
// ---

/**
 * @template TArgs,TReturns
 * @typedef {object} WgslFn
 * @prop {'fn'} type
 * @prop {TArgs} args
 * @prop {TReturns} returns
 */
const fn =
  /**@type{<TArgs extends unknown[] | [],TReturns>(args:TArgs,returns:TReturns)=>WgslFn<TArgs, TReturns>}*/ (
    (args, returns) => ({
      type: 'fn',
      args,
      returns,
    })
  );

// ---
// Definitions
// ---

export const half = fn([f32], f32);
export const double = fn([f32], f32);
export const add = fn([f32, f32], f32);

export const Gradient = struct({
  from: vec3f,
  to: vec3f,
});
