// AUTO-GENERATED BY WESL. Original filename: ./alpha.wesl
// @ts-check

import { fn, f32, struct, vec3f } from 'wgsl-as-js';

// ---
// Function types
// ---

// ---
// Definitions
// ---

export const half = fn(
  'half',
  [f32],
  f32,
  `(value: f32) -> f32 {
  return value * 0.5;
}`
);

export const double = fn(
  'double',
  [f32],
  f32,
  `(value: f32) -> f32 {
  return value * 2.;
}`
);

export const add = fn(
  'add',
  [f32, f32],
  f32,
  `(a: f32, b: f32) -> f32 {
  return a + b;
}`
);

export const Gradient = struct('Gradient', {
  from: vec3f,
  to: vec3f,
});
