// AUTO-GENERATED BY WESL. Original filename: ./beta.wesl
// @ts-check

import { fn } from 'wgsl-as-js';

// ---
// Definitions
// ---

import { double, Gradient } from './alpha.js';

export const create_red_to_blue_gradient = fn(
  'create_red_to_blue_gradient',
  [],
  Gradient,
  [
    '() -> ',
    Gradient,
    ` {
  var result: `,
    Gradient,
    `;
  result.from = vec3f(1., 0., 0.);
  result.to = vec3f(0., 0., `,
    double,
    `(0.5));
  return result;
}`,
  ]
);
